### PR TITLE
More work towards proper testing

### PR DESCRIPTION
**Pull request by tvolkert**
- Add stub tests for Directory. Please review for coverage;
  impl will come later
- Rename tests to follow common pattern
- Fix some cases where we weren't matching the behavior of
  dart:io libraries

### CODE REVIEW

**Comment by tvolkert** [comment]
@johnmccutchan @cbracken @matanlurey

**Comment by johnmccutchan** [comment]
LGTM

**Comment by cbracken** [comment]
lgtm

**Comment by matanlurey** [comment]
LGTM!

**Pull request merged**
