### PR TITLE
Support browser contexts in package:file

### PR DESCRIPTION
**Pull request by tvolkert**
This change uses conditional imports to support browser-based
Dart usage of this package. For non-VM users, this will export
the subset of the dart:io interface that is required by this
package, whereas VM users will simply get dart:io itself.

### CODE REVIEW

**Comment by tvolkert** [comment]
@matanlurey @lrhn @cbracken @johnmccutchan

**Comment by johnmccutchan** [comment]
LGTM.

This is the first time I've really seen the conditional imports / exports syntax. Kind of odd to have the 'if' after the else.

**Comment by tvolkert** [comment]
Ping me offline - it appears they do work inside Google.

**Comment by matanlurey** [comment]
Approved. This won't work with DDC, but it doesn't work in the browser at all (yet). LGTM.

**Pull request merged**
